import Head from "next/head";
import styles from "../../styles/Slug.module.css";
import { GraphQLClient, gql } from "graphql-request";

const graphcms = new GraphQLClient(
  "https://api-eu-west-2.graphcms.com/v2/cl49m8g0316i901z6ceh30363/master"
);

const QUERY = gql`
  query Post($slug: String!) {
    post(where: { slug: $slug }) {
      id
      title
      slug
      datePublished
      author {
        id
        name
        avatar {
          url
        }
      }
      content {
        html
      }

      coverPhoto {
        id
        url
      }
    }
  }
`;

const SLUGLIST = gql`
  {
    posts {
      slug
    }
  }
`;

export async function getStaticPaths() {
  const { posts } = await graphcms.request(SLUGLIST);
  return {
    paths: posts.map((posts) => ({ params: { slug: posts.slug } })),
    fallback: false,
  };
}
export async function getStaticProps({ params }) {
  const slug = params.slug;
  const data = await graphcms.request(QUERY, { slug });
  const post = data.post;
  return {
    props: {
      post,
    },
    revalidate: 10,
  };
}

const Article = ({ post }) => {
  return (
    <>
      <Head>
        <title>Lingfield Advent Schools - {post.title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
          integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer"
        /> */}
      </Head>

      <main className={styles.blog}>
        <div className={styles.blogHead}>
          <img src={post.coverPhoto.url} alt="" className={styles.cover} />
        </div>
        <h2>{post.title}</h2>

        <div className={styles.title}>
          <div className={styles.profile}>
            <img src={post.author.avatar.url} alt="" />
          </div>

          <div className={styles.authtext}>
            <div>
              <i
                className="fa-solid fa-user"
                style={{ paddingRight: "5px", color: "#437f97" }}
              ></i>
              <h4>Published By {post.author.name}</h4>
            </div>

            <div>
              <i
                className="fa-solid fa-calendar-days"
                style={{ paddingRight: "5px", color: "#437f97" }}
              ></i>
              <h4 className={styles.date}>{post.datePublished}</h4>
            </div>
          </div>
        </div>

        <div
          className={styles.content}
          dangerouslySetInnerHTML={{ __html: post.content.html }}
        ></div>
      </main>
    </>
  );
};

export default Article;
