import Head from "next/head";
import styles from "../styles/News.module.css";
import { GraphQLClient, gql } from "graphql-request";
import BlogCard from "../components/BlogCard";
import Location from "../components/Location";

const graphcms = new GraphQLClient(
  "https://api-eu-west-2.graphcms.com/v2/cl49m8g0316i901z6ceh30363/master"
);

const QUERY = gql`
  {
    posts {
      id
      title
      datePublished
      slug
      content {
        html
      }
      author {
        name
        avatar {
          url
        }
      }
      coverPhoto {
        url
      }
    }
  }
`;

export async function getStaticProps() {
  const { posts } = await graphcms.request(QUERY);
  return {
    props: {
      posts,
    },
    revalidate: 10,
  };
}

export default function News({ posts }) {
  return (
    <div className={styles.container}>
      <Head>
        <title>lingfield Advent Schools - School News</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {/* <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css"
          integrity="sha512-KfkfwYDsLkIlwQp6LFnl8zNdLGxu9YAA1QvwINks4PhcElQSvqcyVLLD9aMhXd13uQjoXtEKNosOWaZqXgel0g=="
          crossorigin="anonymous"
          referrerpolicy="no-referrer"
        /> */}
      </Head>
      <Location
        home="Home"
        page="News &amp; Events"
        subpage="Lingfield Advent Schools News"
      />
      <div className={styles.container}>
        <h2 className={styles.heading2}>Lingfield Advent Schools News</h2>
      </div>

      <main className={styles.main}>
        {posts.map((post) => (
          <BlogCard
            title={post.title}
            author={post.author}
            coverPhoto={post.coverPhoto}
            key={post.id}
            datePublished={post.datePublished}
            content={post.content.html}
            slug={post.slug}
          />
        ))}
      </main>
    </div>
  );
}
